### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by MRIIOT** [frangoteam/FUXA#205]
Not reproducible yet.

```
root@5368cd5e2b6f:/usr/src/app/FUXA/server# cat /root/.npm/_logs/2021-10-10T15_31_43_711Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.15
3 info using node@v14.18.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle fuxa-server@1.1.2-489~prestart: fuxa-server@1.1.2-489
6 info lifecycle fuxa-server@1.1.2-489~start: fuxa-server@1.1.2-489
7 verbose lifecycle fuxa-server@1.1.2-489~start: unsafe-perm in lifecycle true
8 verbose lifecycle fuxa-server@1.1.2-489~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/app/FUXA/server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle fuxa-server@1.1.2-489~start: CWD: /usr/src/app/FUXA/server
10 silly lifecycle fuxa-server@1.1.2-489~start: Args: [ '-c', 'node main.js' ]
11 silly lifecycle fuxa-server@1.1.2-489~start: Returned: code: 137  signal: null
12 info lifecycle fuxa-server@1.1.2-489~start: Failed to exec start script
13 verbose stack Error: fuxa-server@1.1.2-489 start: `node main.js`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid fuxa-server@1.1.2-489
15 verbose cwd /usr/src/app/FUXA/server
16 verbose Linux 5.10.52-v7l+
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v14.18.0
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 137
22 error fuxa-server@1.1.2-489 start: `node main.js`
22 error Exit status 137
23 error Failed at the fuxa-server@1.1.2-489 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
root@5368cd5e2b6f:/usr/src/app/FUXA/server# 
```

**Comment by MRIIOT** [comment]
Here is another one.

```
    at Database.<anonymous> (/usr/src/app/FUXA/server/node_modules/sqlite3/lib/sqlite3.js:18:25)
,    at /usr/src/app/FUXA/server/runtime/storage/daqnode.js:541:23
,    at new Promise (<anonymous>)
,    at _insertTagToMap (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:539:16)
,    at MQTTclient.DaqNode.addDaqValues [as addDaq] (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:191:44)
,    at MQTTclient.polling (/usr/src/app/FUXA/server/runtime/devices/mqtt/index.js:144:34)
,    at Device.polling (/usr/src/app/FUXA/server/runtime/devices/device.js:141:14)
,    at Timeout._onTimeout (/usr/src/app/FUXA/server/runtime/devices/device.js:156:22)
,    at listOnTimeout (internal/timers.js:557:17)
,    at processTimers (internal/timers.js:500:7)
,--> in Database#run("INSERT INTO data (id, name, type) VALUES('t_6dee61b7-a3614793','ff[a]','json'); SELECT last_insert_rowid() FROM data", [Function (anonymous)])
,    at /usr/src/app/FUXA/server/runtime/storage/daqnode.js:541:23
,    at new Promise (<anonymous>)
,    at _insertTagToMap (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:539:16)
,    at MQTTclient.DaqNode.addDaqValues [as addDaq] (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:191:44)
,    at MQTTclient.polling (/usr/src/app/FUXA/server/runtime/devices/mqtt/index.js:144:34)
,    at Device.polling (/usr/src/app/FUXA/server/runtime/devices/device.js:141:14)
,    at Timeout._onTimeout (/usr/src/app/FUXA/server/runtime/devices/device.js:156:22)
,    at listOnTimeout (internal/timers.js:557:17)
,    at processTimers (internal/timers.js:500:7)
,2021-10-10T15:44:56.123Z [ERR] 	daqstorage.add-daq-values addDaqfnc failed! 'd_a07a70c6-c4ec486a' undefined
,(node:19) UnhandledPromiseRejectionWarning: ReferenceError: _checkWorking is not defined
,    at /usr/src/app/FUXA/server/runtime/storage/daqnode.js:214:25
,(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 152)
,
,> fuxa-server@1.1.2-489 start /usr/src/app/FUXA/server
,> node main.js
,
,2021-10-10T15:45:52.404Z [INF] 	FUXA V.1.1.2-489
,2021-10-10T15:45:53.539Z [INF] 	FUXA init in  1194ms.
,2021-10-10T15:45:53.578Z [INF] 	'mqtt' created
,2021-10-10T15:45:53.590Z [INF] 	'mqtt' start
,2021-10-10T15:45:53.598Z [INF] 	FUXA started!
,2021-10-10T15:45:53.610Z [INF] 	WebServer is running http://127.0.0.1:1881/
,2021-10-10T15:45:53.835Z [INF] 	'mqtt' connected!
,2021-10-10T15:45:57.227Z [INF] 	socket.io client connected
,GET /api/settings 304 9.246 ms - -
,GET /api/settings 304 2.281 ms - -
,GET /api/settings 304 1.465 ms - -
,GET /api/project 304 43.661 ms - -
,2021-10-10T15:46:05.972Z [INF] 	socket.io client connected
,POST /api/projectData 200 53.738 ms - -
,GET /api/settings 304 2.626 ms - -
,GET /api/settings 304 2.441 ms - -
,GET /api/settings 304 2.528 ms - -
,2021-10-10T15:46:13.117Z [INF] 	socket.io client connected
,GET /api/project 200 25.424 ms - 320644
,POST /api/projectData 200 54.176 ms - -
,GET /api/settings 304 7.001 ms - -
,GET /api/settings 304 1.379 ms - -
,GET /api/settings 304 1.803 ms - -
,2021-10-10T15:46:42.212Z [INF] 	socket.io client connected
,GET /api/project 200 22.884 ms - 320644
,2021-10-10T15:47:19.021Z [INF] 	socket.io client connected
,2021-10-10T15:47:47.596Z [INF] 	socket.io client connected
,2021-10-10T15:48:46.976Z [INF] 	socket.io client connected
,2021-10-10T15:49:14.973Z [INF] 	socket.io client connected
,2021-10-10T15:49:58.024Z [INF] 	socket.io client connected
,2021-10-10T15:50:44.024Z [INF] 	socket.io client connected
,2021-10-10T15:51:26.976Z [INF] 	socket.io client connected
,2021-10-10T15:52:12.084Z [INF] 	socket.io client connected
,2021-10-10T15:52:56.483Z [INF] 	socket.io client connected
,2021-10-10T15:53:29.008Z [INF] 	socket.io client connected
,2021-10-10T15:54:25.063Z [INF] 	socket.io client connected
,2021-10-10T15:54:47.937Z [INF] 	socket.io client connected
,2021-10-10T15:55:52.396Z [INF] 	socket.io client connected
,2021-10-10T15:56:21.159Z [INF] 	socket.io client connected
,POST /api/projectData 200 49.456 ms - -
,POST /api/projectData 200 30.333 ms - -
,GET /api/plugins 304 83.441 ms - -
,2021-10-10T15:57:22.691Z [INF] 	socket.io client connected
,2021-10-10T15:57:33.945Z [INF] 	socket.io client connected
,2021-10-10T15:58:08.197Z [INF] 	'mqtt' stop
,POST /api/projectData 200 1059.368 ms - -
,2021-10-10T15:58:08.224Z [WAR] 	'mqtt' client close mqtt://mosquitto:1883
,2021-10-10T15:58:08.242Z [INF] 	'mqtt' start
,2021-10-10T15:58:08.251Z [INF] 	'mqtt' connected!
,2021-10-10T15:58:13.601Z [INF] 	'mqtt' stop
,2021-10-10T15:58:13.612Z [WAR] 	'mqtt' client close mqtt://mosquitto:1883
,2021-10-10T15:58:13.670Z [INF] 	'mqtt' created
,2021-10-10T15:58:13.686Z [INF] 	'mqtt' start
,2021-10-10T15:58:13.689Z [INF] 	runtime.update-project: restart!
,POST /api/project 200 946.004 ms - -
,2021-10-10T15:58:13.717Z [INF] 	'mqtt' connected!
,GET /api/project 200 26.027 ms - 320819
,POST /api/projectData 200 31.140 ms - -
,2021-10-10T15:58:41.080Z [INF] 	socket.io client connected
,POST /api/projectData 200 52.184 ms - -
,POST /api/projectData 200 29.274 ms - -
,POST /api/projectData 200 51.152 ms - -
,GET /api/settings 304 4.146 ms - -
,GET /api/settings 304 1.436 ms - -
,GET /api/settings 304 2.784 ms - -
,2021-10-10T15:58:51.800Z [INF] 	socket.io client connected
,GET /api/project 200 16.042 ms - 320586
,2021-10-10T15:59:34.140Z [INF] 	socket.io client connected
,POST /api/projectData 200 54.834 ms - -
,POST /api/projectData 200 142.006 ms - -
,2021-10-10T16:00:19.434Z [WAR] 	daqstorage.data-overload! 'd_a07a70c6-c4ec486a'
,POST /api/projectData 200 59.550 ms - -
,GET /api/plugins 304 59.496 ms - -
,POST /api/projectData 200 106.593 ms - -
,GET /api/device?query=security&name=d_a07a70c6-c4ec486a 304 8.337 ms - -
,2021-10-10T16:11:14.187Z [INF] 	socket.io client connected
,2021-10-10T16:15:04.224Z [INF] 	socket.io client connected
,2021-10-10T17:14:07.774Z [INF] 	socket.io client connected
,GET /api/settings 304 5.854 ms - -
,2021-10-10T17:14:11.288Z [INF] 	socket.io client connected
,GET /api/settings 304 1.658 ms - -
,GET /api/project 200 16.248 ms - 319417
,POST /api/projectData 200 80.479 ms - -
,POST /api/projectData 200 44.941 ms - -
,POST /api/projectData 200 32.726 ms - -
,POST /api/projectData 200 35.725 ms - -
,GET /api/settings 304 14.140 ms - -
,2021-10-10T17:15:50.900Z [INF] 	socket.io client connected
,GET /api/settings 304 3.869 ms - -
,GET /api/project 200 19.918 ms - 319446
,2021-10-10T17:26:09.624Z [INF] 	socket.io client connected
,2021-10-10T17:56:37.888Z [INF] 	socket.io client connected
,2021-10-10T18:15:04.090Z [INF] 	socket.io client connected
,2021-10-10T18:31:39.098Z [INF] 	socket.io client connected
,2021-10-10T18:45:19.622Z [INF] 	socket.io client connected
,2021-10-10T19:06:29.374Z [INF] 	socket.io client connected
,2021-10-10T20:07:23.111Z [INF] 	socket.io client connected
,2021-10-10T20:31:15.784Z [INF] 	socket.io client connected
,2021-10-10T21:28:41.761Z [INF] 	socket.io client connected
,2021-10-10T22:09:16.385Z [INF] 	socket.io client connected
,2021-10-10T23:20:53.641Z [INF] 	socket.io client connected
,2021-10-11T00:01:52.714Z [INF] 	socket.io client connected
,2021-10-11T00:02:58.188Z [INF] 	socket.io client connected
,2021-10-11T00:04:37.108Z [INF] 	socket.io client connected
,2021-10-11T00:06:33.207Z [INF] 	socket.io client connected
,2021-10-11T00:09:30.736Z [INF] 	socket.io client connected
,2021-10-11T00:17:37.724Z [INF] 	socket.io client connected
,2021-10-11T00:19:22.548Z [INF] 	socket.io client connected
,POST /api/projectData 200 112.214 ms - -
,POST /api/projectData 200 52.565 ms - -
,GET /api/plugins 304 682.030 ms - -
,2021-10-11T00:20:43.171Z [INF] 	'mqtt' stop
,POST /api/projectData 200 51.872 ms - -
,2021-10-11T00:20:43.200Z [WAR] 	'mqtt' client close mqtt://mosquitto:1883
,2021-10-11T00:20:43.207Z [INF] 	'mqtt' start
,2021-10-11T00:20:43.211Z [INF] 	'mqtt' stop
,2021-10-11T00:20:43.213Z [INF] 	'mqtt' start
,POST /api/projectData 200 58.254 ms - -
,2021-10-11T00:20:43.222Z [INF] 	'mqtt' stop
,2021-10-11T00:20:43.228Z [INF] 	'mqtt' start
,POST /api/projectData 200 75.975 ms - -
,2021-10-11T00:20:43.246Z [INF] 	'mqtt' stop
,2021-10-11T00:20:43.250Z [INF] 	'mqtt' start
,POST /api/projectData 200 93.391 ms - -
,2021-10-11T00:20:43.275Z [INF] 	'mqtt' stop
,2021-10-11T00:20:43.276Z [INF] 	'mqtt' start
,POST /api/projectData 200 125.824 ms - -
,2021-10-11T00:20:43.320Z [INF] 	'mqtt' connected!
,2021-10-11T00:20:43.325Z [INF] 	'mqtt' connected!
,2021-10-11T00:20:43.327Z [INF] 	'mqtt' connected!
,2021-10-11T00:20:43.329Z [INF] 	'mqtt' connected!
,2021-10-11T00:20:43.334Z [INF] 	'mqtt' connected!
,2021-10-11T00:20:43.339Z [INF] 	'mqtt' stop
,POST /api/projectData 200 174.354 ms - -
,2021-10-11T00:20:43.342Z [WAR] 	'mqtt' client close mqtt://mosquitto:1883
,2021-10-11T00:20:43.344Z [INF] 	'mqtt' start
,2021-10-11T00:20:43.351Z [INF] 	'mqtt' connected!
,2021-10-11T00:20:43.402Z [INF] 	'mqtt' stop
,POST /api/projectData 200 27.667 ms - -
,2021-10-11T00:20:43.405Z [WAR] 	'mqtt' client close mqtt://mosquitto:1883
,2021-10-11T00:20:43.407Z [INF] 	'mqtt' start
,2021-10-11T00:20:43.412Z [INF] 	'mqtt' connected!
,2021-10-11T00:20:43.459Z [INF] 	'mqtt' stop
,POST /api/projectData 200 35.838 ms - -
,2021-10-11T00:20:43.462Z [WAR] 	'mqtt' client close mqtt://mosquitto:1883
,2021-10-11T00:20:43.463Z [INF] 	'mqtt' start
,2021-10-11T00:20:43.471Z [INF] 	'mqtt' connected!
,(node:20) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 tag-value:changed listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
,(Use `node --trace-warnings ...` to show where the warning was created)
,2021-10-11T00:20:48.457Z [INF] 	'mqtt' stop
,2021-10-11T00:20:48.470Z [WAR] 	'mqtt' client close mqtt://mosquitto:1883
,2021-10-11T00:20:48.495Z [INF] 	'mqtt' created
,2021-10-11T00:20:48.522Z [INF] 	'mqtt' start
,2021-10-11T00:20:48.524Z [INF] 	runtime.update-project: restart!
,POST /api/project 200 321.317 ms - -
,2021-10-11T00:20:48.537Z [INF] 	'mqtt' connected!
,GET /api/project 200 11.518 ms - 11559
,POST /api/projectData 200 83.476 ms - -
,2021-10-11T00:21:03.114Z [ERR] 	daqstorage.add-daq-value _insertTagToMap failed! 'd_a07a70c6-c4ec486a' Error: SQLITE_MISUSE: Database is closed
,    at Database.<anonymous> (/usr/src/app/FUXA/server/node_modules/sqlite3/lib/sqlite3.js:18:25)
,    at /usr/src/app/FUXA/server/runtime/storage/daqnode.js:541:23
,    at new Promise (<anonymous>)
,    at _insertTagToMap (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:539:16)
,    at MQTTclient.DaqNode.addDaqValues [as addDaq] (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:191:44)
,    at MQTTclient.polling (/usr/src/app/FUXA/server/runtime/devices/mqtt/index.js:144:34)
,    at Device.polling (/usr/src/app/FUXA/server/runtime/devices/device.js:141:14)
,    at Timeout._onTimeout (/usr/src/app/FUXA/server/runtime/devices/device.js:156:22)
,    at listOnTimeout (internal/timers.js:557:17)
,    at processTimers (internal/timers.js:500:7)
,--> in Database#run("INSERT INTO data (id, name, type) VALUES('t_a48eb05e-05044acf','fuxa/job[active]','json'); SELECT last_insert_rowid() FROM data", [Function (anonymous)])
,    at /usr/src/app/FUXA/server/runtime/storage/daqnode.js:541:23
,    at new Promise (<anonymous>)
,    at _insertTagToMap (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:539:16)
,    at MQTTclient.DaqNode.addDaqValues [as addDaq] (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:191:44)
,    at MQTTclient.polling (/usr/src/app/FUXA/server/runtime/devices/mqtt/index.js:144:34)
,    at Device.polling (/usr/src/app/FUXA/server/runtime/devices/device.js:141:14)
,    at Timeout._onTimeout (/usr/src/app/FUXA/server/runtime/devices/device.js:156:22)
,    at listOnTimeout (internal/timers.js:557:17)
,    at processTimers (internal/timers.js:500:7)
,(node:20) UnhandledPromiseRejectionWarning: ReferenceError: _checkWorking is not defined
,    at /usr/src/app/FUXA/server/runtime/storage/daqnode.js:214:25
,(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
,(node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
,POST /api/projectData 200 31.910 ms - -
,POST /api/projectData 200 50.268 ms - -
,2021-10-11T00:21:27.067Z [INF] 	socket.io client connected
,POST /api/projectData 200 46.789 ms - -
,POST /api/projectData 200 35.262 ms - -
,2021-10-11T00:22:03.180Z [ERR] 	daqstorage.add-daq-value _insertTagToMap failed! 'd_a07a70c6-c4ec486a' Error: SQLITE_MISUSE: Database is closed
,    at Database.<anonymous> (/usr/src/app/FUXA/server/node_modules/sqlite3/lib/sqlite3.js:18:25)
,    at /usr/src/app/FUXA/server/runtime/storage/daqnode.js:541:23
,    at new Promise (<anonymous>)
,    at _insertTagToMap (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:539:16)
,    at MQTTclient.DaqNode.addDaqValues [as addDaq] (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:191:44)
,    at MQTTclient.polling (/usr/src/app/FUXA/server/runtime/devices/mqtt/index.js:144:34)
,    at Device.polling (/usr/src/app/FUXA/server/runtime/devices/device.js:141:14)
,    at Timeout._onTimeout (/usr/src/app/FUXA/server/runtime/devices/device.js:156:22)
,    at listOnTimeout (internal/timers.js:557:17)
,    at processTimers (internal/timers.js:500:7)
,--> in Database#run("INSERT INTO data (id, name, type) VALUES('t_a48eb05e-05044acf','fuxa/job[active]','json'); SELECT last_insert_rowid() FROM data", [Function (anonymous)])
,    at /usr/src/app/FUXA/server/runtime/storage/daqnode.js:541:23
,    at new Promise (<anonymous>)
,    at _insertTagToMap (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:539:16)
,    at MQTTclient.DaqNode.addDaqValues [as addDaq] (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:191:44)
,    at MQTTclient.polling (/usr/src/app/FUXA/server/runtime/devices/mqtt/index.js:144:34)
,    at Device.polling (/usr/src/app/FUXA/server/runtime/devices/device.js:141:14)
,    at Timeout._onTimeout (/usr/src/app/FUXA/server/runtime/devices/device.js:156:22)
,    at listOnTimeout (internal/timers.js:557:17)
,    at processTimers (internal/timers.js:500:7)
,(node:20) UnhandledPromiseRejectionWarning: ReferenceError: _checkWorking is not defined
,    at /usr/src/app/FUXA/server/runtime/storage/daqnode.js:214:25
,    at processTicksAndRejections (internal/process/task_queues.js:95:5)
,(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 18)
,POST /api/projectData 200 31.810 ms - -
,POST /api/projectData 200 37.141 ms - -
,POST /api/projectData 200 38.634 ms - -
,2021-10-11T00:23:03.301Z [ERR] 	daqstorage.add-daq-value _insertTagToMap failed! 'd_a07a70c6-c4ec486a' Error: SQLITE_MISUSE: Database is closed
,    at Database.<anonymous> (/usr/src/app/FUXA/server/node_modules/sqlite3/lib/sqlite3.js:18:25)
,    at /usr/src/app/FUXA/server/runtime/storage/daqnode.js:541:23
,    at new Promise (<anonymous>)
,    at _insertTagToMap (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:539:16)
,    at MQTTclient.DaqNode.addDaqValues [as addDaq] (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:191:44)
,    at MQTTclient.polling (/usr/src/app/FUXA/server/runtime/devices/mqtt/index.js:144:34)
,    at Device.polling (/usr/src/app/FUXA/server/runtime/devices/device.js:141:14)
,    at Timeout._onTimeout (/usr/src/app/FUXA/server/runtime/devices/device.js:156:22)
,    at listOnTimeout (internal/timers.js:557:17)
,    at processTimers (internal/timers.js:500:7)
,--> in Database#run("INSERT INTO data (id, name, type) VALUES('t_a48eb05e-05044acf','fuxa/job[active]','json'); SELECT last_insert_rowid() FROM data", [Function (anonymous)])
,    at /usr/src/app/FUXA/server/runtime/storage/daqnode.js:541:23
,    at new Promise (<anonymous>)
,    at _insertTagToMap (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:539:16)
,    at MQTTclient.DaqNode.addDaqValues [as addDaq] (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:191:44)
,    at MQTTclient.polling (/usr/src/app/FUXA/server/runtime/devices/mqtt/index.js:144:34)
,    at Device.polling (/usr/src/app/FUXA/server/runtime/devices/device.js:141:14)
,    at Timeout._onTimeout (/usr/src/app/FUXA/server/runtime/devices/device.js:156:22)
,    at listOnTimeout (internal/timers.js:557:17)
,    at processTimers (internal/timers.js:500:7)
,(node:20) UnhandledPromiseRejectionWarning: ReferenceError: _checkWorking is not defined
,    at /usr/src/app/FUXA/server/runtime/storage/daqnode.js:214:25
,    at runMicrotasks (<anonymous>)
,    at processTicksAndRejections (internal/process/task_queues.js:95:5)
,(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 27)
,POST /api/projectData 200 56.956 ms - -
,POST /api/projectData 200 60.254 ms - -
,POST /api/projectData 200 88.731 ms - -
,POST /api/projectData 200 55.675 ms - -
,2021-10-11T00:24:03.390Z [ERR] 	daqstorage.add-daq-value _insertTagToMap failed! 'd_a07a70c6-c4ec486a' Error: SQLITE_MISUSE: Database is closed
,    at Database.<anonymous> (/usr/src/app/FUXA/server/node_modules/sqlite3/lib/sqlite3.js:18:25)
,    at /usr/src/app/FUXA/server/runtime/storage/daqnode.js:541:23
,    at new Promise (<anonymous>)
,    at _insertTagToMap (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:539:16)
,    at MQTTclient.DaqNode.addDaqValues [as addDaq] (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:191:44)
,    at MQTTclient.polling (/usr/src/app/FUXA/server/runtime/devices/mqtt/index.js:144:34)
,    at Device.polling (/usr/src/app/FUXA/server/runtime/devices/device.js:141:14)
,    at Timeout._onTimeout (/usr/src/app/FUXA/server/runtime/devices/device.js:156:22)
,    at listOnTimeout (internal/timers.js:557:17)
,    at processTimers (internal/timers.js:500:7)
,--> in Database#run("INSERT INTO data (id, name, type) VALUES('t_a48eb05e-05044acf','fuxa/job[active]','json'); SELECT last_insert_rowid() FROM data", [Function (anonymous)])
,    at /usr/src/app/FUXA/server/runtime/storage/daqnode.js:541:23
,    at new Promise (<anonymous>)
,    at _insertTagToMap (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:539:16)
,    at MQTTclient.DaqNode.addDaqValues [as addDaq] (/usr/src/app/FUXA/server/runtime/storage/daqnode.js:191:44)
,    at MQTTclient.polling (/usr/src/app/FUXA/server/runtime/devices/mqtt/index.js:144:34)
,    at Device.polling (/usr/src/app/FUXA/server/runtime/devices/device.js:141:14)
,    at Timeout._onTimeout (/usr/src/app/FUXA/server/runtime/devices/device.js:156:22)
,    at listOnTimeout (internal/timers.js:557:17)
,    at processTimers (internal/timers.js:500:7)
,(node:20) UnhandledPromiseRejectionWarning: ReferenceError: _checkWorking is not defined
,    at /usr/src/app/FUXA/server/runtime/storage/daqnode.js:214:25
,    at runMicrotasks (<anonymous>)
,    at processTicksAndRejections (internal/process/task_queues.js:95:5)
,(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 36)
```

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.
