### ISSUE TITLE
Cannot read properties of undefined (reading 'name') in console

### ISSUE THREAD

**Issue by balincagabrielalin** [frangoteam/FUXA#476]
When I refresh the page with device settings, it gives me this error in the browser's console :

    ERROR TypeError: Cannot read properties of undefined (reading 'name')
        at device-list.component.ts:109:35
        at Array.forEach (<anonymous>)
        at push../app/device/device-list/device-list.component.ts.DeviceListComponent.setSelectedDevice (device-list.component.ts:108:37)
        at push../app/device/device-list/device-list.component.ts.DeviceListComponent.mapTags (device-list.component.ts:88:14)
        at device.component.ts:56:29
        at SafeSubscriber.schedulerFn [as _next] (core.js:13516:35)
        at push.../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:196:1)
        at push.../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next (Subscriber.js:134:1)
        at push.../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next (Subscriber.js:77:1)
        at push.../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:54:1)`

Image :
![image](https://user-images.githubusercontent.com/32384258/189333445-fb23c99f-3e2f-4ced-9f76-a46826b2e721.png)

Probably another default value is missing.

**Comment by unocelli** [comment]
I am going to close this as resolved. let me know if you have any issues.
