### ISSUE TITLE
It takes extremely long (10-20 minutes) to change the view period on the chart.

### ISSUE THREAD

**Issue by microdeth** [frangoteam/FUXA#746]
Hi, on the historical chart containing the temperature and humidity data when I switch from the last 8 hours to last 3 days, for example, it takes 10-20 minutes. Overall object scheme contains less than 10 data points, only device is connected is our self-designed PLC which have OPC UA onboard.
Thanks,
Dima.

**Comment by microdeth** [comment]
Server runs at R5 5400U (8GB RAM), client is i7 11700 notebook (16GB Ram).

**Comment by unocelli** [comment]
Hi, sorry for the delay.
we would be very grateful if you would try to investigate in more detail, console error of the frontend and backend, how many tags are you saving? have you tried to re-initialise everything by deleting the current database (_db folder)

**Comment by microdeth** [comment]
Hi Umberto,
Thanks for your response!
Overall tags are 8, but only 2 of them are stored:
[image: image.png]
No errors are seen from Frontend except it asks to wait for the page, the
only errors on the backend I've seen so far are:
[image: image.png]
Now somehow things become much better -- the request to show data for the
last 30 days takes only ~7 min (which is not acceptable for the frontend
anyhow).
I suspect that it can be connected with the overall server
performance (it's only a Ryzen 5 5400U CPU with 8 Mb RAM), but I need to
confirm that server upgrade may help and this is not some indexing issue.
You can access the test frontend on http://microdeth.tplinkdns.com:1881 and
check it yourself.
One more note -- when you choose the data range for the chart using the
clock icon the dropdown value remains the same, e.g. 'last 8 hours'.
[image: image.png] ->
[image: image.png]

Many thanks for your assistance,
Dima.

чт, 30 мар. 2023 г. в 01:59, Umberto Nocelli ***@***.***>:

**Comment by unocelli** [comment]
Hi, sorry for the delay again. Thanks for your investigation.
I would like to have a look at the archived files. can you share it with me? 
have you tried influxdb?

**Comment by microdeth** [comment]
Hi, thanks for your answer.
You can find the archive files here: https://microdeth.tplinkdns.com/owncloud/s/uIcINRiOBBtkHAA
How can I try 'influxdb'?

Best regards,
Dima.

**Comment by unocelli** [comment]
Hi, sorry for the delay.
Thanks for the archive files, we will take a look soon.
About influxdb: you have to install it and configure the access value (token and bucket) to insert in FUXA-Settings
![image](https://user-images.githubusercontent.com/48684550/233734270-c774d081-0402-41ac-9069-3940f7db3684.png)

**Comment by microdeth** [comment]
Thanks, will try to!

Regards,
Dima.

сб, 22 апр. 2023 г., 03:10 Umberto Nocelli ***@***.***>:

**Comment by unocelli** [comment]
is there any news?

**Comment by 885669801** [comment]
> 有消息吗？

Hello, has your problem been solved? How to solve it?

**Comment by andy8601** [comment]
I also have similar problems, and the problem of using influxDB is still the same, which can be stored once a second. At the current test stage, there are only about 5 variables, and the data can be refreshed within a few hours. After more than one day, it takes about 15 seconds to refresh the data of the last 8 hours, during which the page is stuck, and the background will not record the updated stored data. It is necessary to wait until the refresh is successful before re-recording the data, influxDB itself has a similar curve chart function, and the refresh speed is very fast, I think there is still something wrong, although I do not understand. If you really can't solve this problem, I suggest that the curve function does not call all curve data by default, and you need to manually check the curve data, I believe it will be greatly improved.

**Comment by andy8601** [comment]
The problem has always existed. I tried to replace a server with a higher hardware configuration, and some improvements have been made. At present, the data in the last 8 hours of refreshing has been reduced from the original 15 seconds to 6 seconds. In fact, there is only one core in the work of computing, so it caused the delay. I know that node.js has a “Cluster core” module, but I don't understand it very well. @unocelli Hope you solve this problem soon!

**Comment by unocelli** [comment]
Hi, storage on sqlite is file-based, which has several performance disadvantages, it also depends on the split size of the files, the amount of files in the history...I think it would be more acceptable if we split the range into small queries that populate the diagram as in realtime.
Concerning influxdb: currently the queries go through the FUXA server, we should try querying the database directly.

**Comment by unocelli** [comment]
Hi, The configuration of the DAQ history is decisive. I just added the partial query results for the DAQ data

**Comment by mrHubdoc** [comment]
I have similar issues using InfluxDB. I experience the problem as more significant when I have multiple Y Axes. When I select a 3-day view, it times out on both reading and writing to InfluxDB. See the error below.
Eventually, Fuxa stops. I am happy to provide more information. I really like Fuxa!

```
POST /api/heartbeat 200 - - 2.234 ms
^C2025-03-07T08:06:16.677Z [INF]        'FUXA' stop
2025-03-07T08:06:16.679Z [INF]  '314IFM' stop
2025-03-07T08:06:16.703Z [INF]  FUXA end!
root@fuxa:/home/fuxa# fuxa
2025-03-07T08:09:28.675Z [INF]  FUXA V.1.2.1
2025-03-07T08:09:30.717Z [INF]  FUXA init in  2252ms.
2025-03-07T08:09:31.050Z [INF]  'FUXA' created
2025-03-07T08:09:31.180Z [INF]  '314IFM' created
2025-03-07T08:09:31.181Z [INF]  'FUXA' start
2025-03-07T08:09:31.184Z [INF]  '314IFM' start
2025-03-07T08:09:31.190Z [INF]  FUXA started!
2025-03-07T08:09:31.196Z [INF]  WebServer is running http://127.0.0.1:1881/
2025-03-07T08:09:31.336Z [INF]  socket.io client connected
2025-03-07T08:09:31.410Z [INF]  '314IFM' restored 0/0 values
2025-03-07T08:09:31.411Z [INF]  'FUXA' restored 0/0 values
2025-03-07T08:09:31.521Z [INF]  socket.io client connected
GET /api/settings 304 11.536 ms - -
GET /api/settings 304 - - 11.536 ms
GET /api/settings 200 5.006 ms - 1366
GET /api/settings 200 1366 - 5.006 ms
2025-03-07T08:10:07.650Z [INF]  socket.io client connected
2025-03-07T08:10:07.676Z [INF]  socket.io client connected
GET /api/project 200 15.006 ms - 262065
GET /api/project 200 262065 - 15.006 ms
2025-03-07T08:10:30.158Z [WAR]  '314IFM' working (connection || polling) overload! 1
WARN: Write to InfluxDB failed (attempt: 1). Error: socket hang up
    at connResetException (internal/errors.js:639:14)
    at Socket.socketOnEnd (_http_client.js:499:23)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET'
}
2025-03-07T08:12:21.387Z [ERR]  influxdb-writePoints error! Error: socket hang up
WARN: Write to InfluxDB failed (attempt: 1). Error: socket hang up
    at connResetException (internal/errors.js:639:14)
    at Socket.socketOnEnd (_http_client.js:499:23)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET'
}
2025-03-07T08:12:21.688Z [ERR]  influxdb-writePoints error! Error: socket hang up
WARN: Write to InfluxDB failed (attempt: 1). Error: socket hang up
    at connResetException (internal/errors.js:639:14)
    at Socket.socketOnEnd (_http_client.js:499:23)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET'
}
2025-03-07T08:12:21.697Z [ERR]  influxdb-writePoints error! Error: socket hang up
POST /api/heartbeat 200 561.492 ms - -
POST /api/heartbeat 200 - - 561.492 ms
2025-03-07T08:12:22.400Z [INF]  socket.io client connected
2025-03-07T08:12:22.403Z [INF]  socket.io client connected
2025-03-07T08:12:22.406Z [INF]  socket.io client connected
WARN: Write to InfluxDB failed (attempt: 2). S [RequestTimedOutError]: Request timed out
    at ClientRequest.<anonymous> (/root/.nvm/versions/node/v14.21.3/lib/node_modules/@frangoteam/fuxa/node_modules/@influxdata/influxdb-client/dist/index.js:16:4142)
    at ClientRequest.emit (events.js:400:28)
    at Socket.emitRequestTimeout (_http_client.js:790:9)
    at Object.onceWrapper (events.js:519:28)
    at Socket.emit (events.js:412:35)
    at Socket._onTimeout (net.js:495:8)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
2025-03-07T08:12:44.648Z [WAR]  '314IFM' working (connection || polling) overload! 1
WARN: Write to InfluxDB failed (attempt: 1). S [RequestTimedOutError]: Request timed out
    at ClientRequest.<anonymous> (/root/.nvm/versions/node/v14.21.3/lib/node_modules/@frangoteam/fuxa/node_modules/@influxdata/influxdb-client/dist/index.js:16:4142)
    at ClientRequest.emit (events.js:400:28)
    at Socket.emitRequestTimeout (_http_client.js:790:9)
    at Object.onceWrapper (events.js:519:28)
    at Socket.emit (events.js:412:35)
    at Socket._onTimeout (net.js:495:8)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
2025-03-07T08:13:20.055Z [ERR]  influxdb-writePoints error! RequestTimedOutError: Request timed out
WARN: Write to InfluxDB failed (attempt: 2). S [RequestTimedOutError]: Request timed out
    at ClientRequest.<anonymous> (/root/.nvm/versions/node/v14.21.3/lib/node_modules/@frangoteam/fuxa/node_modules/@influxdata/influxdb-client/dist/index.js:16:4142)
    at ClientRequest.emit (events.js:400:28)
    at Socket.emitRequestTimeout (_http_client.js:790:9)
    at Object.onceWrapper (events.js:519:28)
    at Socket.emit (events.js:412:35)
    at Socket._onTimeout (net.js:495:8)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
2025-03-07T08:13:20.063Z [ERR]  influxdb-writePoints error! RequestTimedOutError: Request timed out
2025-03-07T08:13:20.064Z [ERR]  influxdb-getDaqValue failed! RequestTimedOutError: Request timed out
2025-03-07T08:13:20.071Z [ERR]  influxdb-getDaqValue failed! RequestTimedOutError: Request timed out
2025-03-07T08:13:20.072Z [ERR]  influxdb-getDaqValue failed! RequestTimedOutError: Request timed out
2025-03-07T08:13:24.342Z [ERR]  daq-query: RequestTimedOutError: Request timed out
    at ClientRequest.<anonymous> (/root/.nvm/versions/node/v14.21.3/lib/node_modules/@frangoteam/fuxa/node_modules/@influxdata/influxdb-client/dist/index.js:16:4142)
    at ClientRequest.emit (events.js:400:28)
    at Socket.emitRequestTimeout (_http_client.js:790:9)
    at Object.onceWrapper (events.js:519:28)
    at Socket.emit (events.js:412:35)
    at Socket._onTimeout (net.js:495:8)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
2025-03-07T08:13:24.366Z [ERR]  daq-query: RequestTimedOutError: Request timed out
    at ClientRequest.<anonymous> (/root/.nvm/versions/node/v14.21.3/lib/node_modules/@frangoteam/fuxa/node_modules/@influxdata/influxdb-client/dist/index.js:16:4142)
    at ClientRequest.emit (events.js:400:28)
    at Socket.emitRequestTimeout (_http_client.js:790:9)
    at Object.onceWrapper (events.js:519:28)
    at Socket.emit (events.js:412:35)
    at Socket._onTimeout (net.js:495:8)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
2025-03-07T08:13:24.603Z [INF]  socket.io client connected
2025-03-07T08:13:24.606Z [INF]  socket.io client connected
2025-03-07T08:13:24.608Z [INF]  socket.io client connected
GET /api/resources/widgets?type=widgets 304 101.016 ms - -
GET /api/resources/widgets?type=widgets 304 - - 101.016 ms
POST /api/projectData 200 331.658 ms - -
POST /api/projectData 200 - - 331.658 ms
2025-03-07T08:13:47.075Z [ERR]  influxdb-getDaqValue failed! RequestTimedOutError: Request timed out
2025-03-07T08:14:16.643Z [ERR]  daq-query: RequestTimedOutError: Request timed out
    at ClientRequest.<anonymous> (/root/.nvm/versions/node/v14.21.3/lib/node_modules/@frangoteam/fuxa/node_modules/@influxdata/influxdb-client/dist/index.js:16:4142)
    at ClientRequest.emit (events.js:400:28)
    at Socket.emitRequestTimeout (_http_client.js:790:9)
    at Object.onceWrapper (events.js:519:28)
    at Socket.emit (events.js:412:35)
    at Socket._onTimeout (net.js:495:8)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
POST /api/projectData 200 29593.195 ms - -
POST /api/projectData 200 - - 29593.195 ms
2025-03-07T08:14:16.697Z [ERR]  influxdb-getDaqValue failed! RequestTimedOutError: Request timed out
WARN: Write to InfluxDB failed (attempt: 1). Error: socket hang up
    at connResetException (internal/errors.js:639:14)
    at Socket.socketOnEnd (_http_client.js:499:23)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET'
}
2025-03-07T08:14:23.229Z [ERR]  influxdb-writePoints error! Error: socket hang up
POST /api/heartbeat 200 40.048 ms - -
POST /api/heartbeat 200 - - 40.048 ms
2025-03-07T08:14:23.327Z [WAR]  '314IFM' working (connection || polling) overload! 1
POST /api/heartbeat 200 3.560 ms - -
POST /api/heartbeat 200 - - 3.560 ms
POST /api/heartbeat 200 2.796 ms - -
POST /api/heartbeat 200 - - 2.796 ms
```

**Comment by mrHubdoc** [comment]
" Testing with a shorter time range (e.g., 1 day or a few hours) to see if the issue is related to the data volume."
_Yes, a shorter time frame (1 day) works better._

"Checking InfluxDB performance settings, including query execution time, memory usage, and connection limits."
_I will take a closer look at it._

"Monitoring CPU, memory, and disk I/O usage on both FUXA and InfluxDB servers to detect bottlenecks."
_Fuxa and Influxdb are running on the same virtual environment_

"Optimizing database queries by downsampling data or using aggregated views to reduce the number of points retrieved at once."
_I will take a deeper look into it._

"Trying with fewer Y-axes to determine if multiple axes are contributing to the problem."
_I have several line charts. One has 8 signals and 1 Y-axis, and it works fine. But the line chart with 3 Y-axes and 8 signals is not visible at all over a 3-day period._


"Adjusting polling and write intervals in FUXA to reduce the load on InfluxDB."
_I will test it._

This is the result when I go from 1 day to 2 days (after changing the time from the clock symbol): the graph does not update, only the time axis does.
![Image](https://github.com/user-attachments/assets/38529bc3-daf9-4fc6-ae81-db545fce54fb)


I expressed myself poorly; it is the scale axis that disappears.
![Image](https://github.com/user-attachments/assets/87709c12-7582-4c3e-98ce-22c42dd77e15)
![Image](https://github.com/user-attachments/assets/f33204d9-7bd7-4117-8313-a9d7ed8b795d)
![Image](https://github.com/user-attachments/assets/e99cff0f-9453-4dc6-8866-cb3168b35573)

**Comment by unocelli** [comment]
Hi, about the last chart you have to set Y1Min=-1800 and Y1Max=100

**Comment by unocelli** [comment]
I assume this issue has been resolved in the meantime. I'll close the issue for now, but please feel free to reopen it if it is still relevant or if you would like to continue the discussion.
