### ISSUE TITLE
Scripts functions on client cannot be used inside other scripts functions on client.

### ISSUE THREAD

**Issue by AlexandruAndrei3** [frangoteam/FUXA#808]
Hello, I am changing the color of an object using its id with this code inside a script running on CLIENT.

This is the code inside the script i want to call in another client script.

var obiectId = document.getElementById("SHE_2461a9e7-260b497c");                                 
obiectId.style.fill = "#ff7107"; 

If I am trying to call the change color script in another CLIENT script function this error will result in browser console:
 xa-view.component.ts:762 ReferenceError: ColorShape is not defined
    at eval (eval at <anonymous> (script.service.ts:38:17), <anonymous>:1:1)
    at M._subscribe (script.service.ts:38:17)
    at M._trySubscribe (Observable.js:37:25)
    at Observable.js:31:30
    at e (errorContext.js:19:9)
    at M.subscribe (Observable.js:22:9)
    at n.onRunScript (fuxa-view.component.ts:759:49)
    at n.runEvents (fuxa-view.component.ts:434:22)
    at G.<anonymous> (fuxa-view.component.ts:389:26)
    at v.invokeTask (zone.js:406:31)
(
It seems like a client script cannot be called in another client script. What do you suggest I should do?

**Comment by unocelli** [comment]
Hi, currently, client-side scripts are only executed and not loaded into the scope like server-side scripts. so you cannot refer to the function
